openapi: 3.0.3
info:
  title: Member System - Order History & Course Ownership API
  description: Order tracking and owned courses endpoints
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Development server
  - url: https://api.waterballsa.tw/api
    description: Production server

paths:
  /orders:
    get:
      summary: Get order history
      description: Returns paginated list of user's orders (10 per page, sorted by date newest first)
      operationId: getOrders
      tags:
        - Orders
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number (1-indexed)
        - name: page_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
          description: Items per page
      responses:
        '200':
          description: Order history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /orders/{orderId}:
    get:
      summary: Get order details
      description: Returns detailed information for a specific order
      operationId: getOrderDetail
      tags:
        - Orders
      security:
        - bearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetail'
        '403':
          description: Order belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: FORBIDDEN
                message: 您無權訪問此訂單
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /courses/owned:
    get:
      summary: Get owned courses
      description: Returns list of courses user owns (from completed orders)
      operationId: getOwnedCourses
      tags:
        - Courses
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 20
      responses:
        '200':
          description: Owned courses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnedCoursesResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    OrderListResponse:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/OrderSummary'
        pagination:
          $ref: '#/components/schemas/Pagination'
      required:
        - orders
        - pagination

    OrderSummary:
      type: object
      properties:
        order_id:
          type: string
          format: uuid
        order_number:
          type: string
          example: ORD-20251114-0001
        created_at:
          type: string
          format: date-time
        total_amount:
          type: number
          format: decimal
          example: 1999.00
        payment_status:
          type: string
          enum: [待付款, 已付款, 已完成, 已取消]
          description: Order status in Chinese
      required:
        - order_id
        - order_number
        - created_at
        - total_amount
        - payment_status

    OrderDetail:
      type: object
      properties:
        order_id:
          type: string
          format: uuid
        order_number:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        total_amount:
          type: number
          format: decimal
        payment_status:
          type: string
          enum: [待付款, 已付款, 已完成, 已取消]
        payment_method:
          type: string
          nullable: true
          example: Credit Card
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        subtotal:
          type: number
          format: decimal
          description: Sum of item prices before discount
        discount:
          type: number
          format: decimal
          nullable: true
          description: Discount amount from coupon (null if no coupon)
      required:
        - order_id
        - order_number
        - created_at
        - updated_at
        - total_amount
        - payment_status
        - items
        - subtotal

    OrderItem:
      type: object
      properties:
        item_id:
          type: string
          format: uuid
        course_id:
          type: string
          format: uuid
        course_name:
          type: string
          description: Course title from catalog
        price:
          type: number
          format: decimal
        purchased_at:
          type: string
          format: date-time
      required:
        - item_id
        - course_id
        - course_name
        - price
        - purchased_at

    OwnedCoursesResponse:
      type: object
      properties:
        courses:
          type: array
          items:
            $ref: '#/components/schemas/OwnedCourse'
        pagination:
          $ref: '#/components/schemas/Pagination'
      required:
        - courses
        - pagination

    OwnedCourse:
      type: object
      properties:
        course_id:
          type: string
          format: uuid
        course_title:
          type: string
        instructor:
          type: string
        acquired_date:
          type: string
          format: date-time
          description: When course was acquired (from order completion)
      required:
        - course_id
        - course_title
        - instructor
        - acquired_date

    Pagination:
      type: object
      properties:
        current_page:
          type: integer
          minimum: 1
        page_size:
          type: integer
          minimum: 1
        total_items:
          type: integer
          minimum: 0
        total_pages:
          type: integer
          minimum: 0
      required:
        - current_page
        - page_size
        - total_items
        - total_pages

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
      required:
        - code
        - message
